language: go

install:
  - go get -d -t -v && go build -v

go:
  - 1.13.x
  - 1.12.x
  - 1.11.x
  - tip

script:
  - go vet 
  - go test -v -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
